services:
  3x-ui:
    build: ./3x-ui
    hostname: 3xuilab
    volumes:
      - ./3x-ui/db/:/etc/x-ui/
      - ./3x-ui/logs/:/app/logs/
      # Address from certbot.
      - /etc/letsencrypt/archive/ADDRESS.FROM.CERTBOOT:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    restart: unless-stopped
    expose:
      # Hide standart panel port.
      - 2053:2053
    ports:
      # Inbound port.
      - XXX:XXX
      # Subscription port.
      - XXXXX:XXXXX
  nginx:
    build: ./nginx
    restart: always
    volumes:
      # Address from certbot.
      - /etc/letsencrypt/archive/ADDRESS.FROM.CERTBOOT:/etc/nginx/certs/
    ports:
      # Panel port.
      - XXXXX:XXXXX
    depends_on:
      - 3x-ui
