services:
  3x-ui:
    build: ./3x-ui
    hostname: 3xuilab
    volumes:
      - ./3x-ui/db/:/etc/x-ui/
      - ./3x-ui/logs/:/app/logs/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
    tty: true
    restart: unless-stopped
    expose:
      # Hide standart panel and subscription port.
      - "2053:2053"
      - "2054:2054"
    ports:
      # Inbound port.
      - XXX:XXX
  nginx:
    build: ./nginx
    restart: always
    volumes:
      # Address from certbot.
      - /etc/letsencrypt/archive/ADDRESS.FROM.CERTBOOT:/etc/nginx/certs/

      - /etc/letsencrypt/live/ADDRESS.FROM.CERTBOOT:/etc/letsencrypt/live/ADDRESS.FROM.CERTBOOT:ro
      - /etc/letsencrypt/archive/ADDRESS.FROM.CERTBOOT:/etc/letsencrypt/archive/ADDRESS.FROM.CERTBOOT:ro
    ports:
      # Panel port.
      - XXXXX:XXXXX
      # Subscription port.
      - XXXXX:XXXXX
    depends_on:
      - 3x-ui
